-- Persist the opaque login-subject key on the event row for efficient, auditable correlation.
-- The value is generated by LoginSubjectKeyFactory and must never contain a raw account name.
ALTER TABLE monitoring_security_event
    ADD COLUMN attempted_account_hash VARCHAR(128) NULL COMMENT '登录尝试账号的版本化不可逆关联值'
    AFTER session_id_hash;
