package io.github.jasper.monitoring.api.management;
public enum ManagementOperation { EVENT_READ, ALERT_READ, ALERT_ASSIGNMENT_READ, ALERT_ASSIGN, ALERT_ACKNOWLEDGE, ALERT_INVESTIGATE, ALERT_CLOSE, ALERT_MARK_FALSE_POSITIVE, RULE_READ, RULE_CHANGE, RULE_APPROVE, WHITELIST_READ, WHITELIST_GRANT, WHITELIST_REVOKE, CONTROL_READ, CONTROL_APPROVE, CONTROL_REJECT, CONTROL_RETRY }
