package io.github.jasper.monitoring.api;

/**
 * 可持久化的受控输入质量问题码。
 */
public enum EventInputIssueCode {
    MISSING_DATA_COUNT,
    MISSING_LATENCY_MS,
    MISSING_RESOURCE_ID,
    MISSING_ORG_SCOPE,
    MISSING_SOURCE_IP,
    MISSING_ATTEMPTED_ACCOUNT_HASH,
    MISSING_TARGET_USER_ID,
    MISSING_REASON_CODE,
    MISSING_FACT,
    INVALID_FACT,
    INVALID_SOURCE_IP,
    INVALID_PARAMETER_VALUE,
    UNRESOLVED_PARAMETER_PATH,
    PROTECTED_FACT_OVERRIDE,
    EVENT_ENRICHER_REJECTED
}
