package io.github.jasper.monitoring.api.error;

import io.github.jasper.monitoring.api.code.CodeFamily;
import io.github.jasper.monitoring.api.code.GovernedCode;

/** Stable, machine-readable monitoring failure codes. */
public enum MonitoringErrorCode implements GovernedCode {
    REQUIRED_FIELD_MISSING("MON.API.REQUIRED_FIELD_MISSING"),
    INVALID_FIELD_VALUE("MON.API.INVALID_FIELD_VALUE"),
    UNSAFE_EVENT_ATTRIBUTE("MON.API.UNSAFE_EVENT_ATTRIBUTE"),
    ACTION_NOT_REGISTERED("MON.API.ACTION_NOT_REGISTERED"),
    CONFLICTING_ACTION_DEFINITION("MON.API.CONFLICTING_ACTION_DEFINITION"),
    RULE_REGISTRY_FROZEN("MON.API.RULE_REGISTRY_FROZEN"),
    DUPLICATE_CONTROL_BINDING("MON.API.DUPLICATE_CONTROL_BINDING"),
    INVALID_CONTROL_TRIGGER("MON.API.INVALID_CONTROL_TRIGGER"),
    DUPLICATE_INTERNAL_RULE_ID("MON.API.DUPLICATE_INTERNAL_RULE_ID"),
    ACTION_CATALOG_FROZEN("MON.API.ACTION_CATALOG_FROZEN"),
    MANAGEMENT_VALIDATION_FAILED("MON.API.MANAGEMENT_VALIDATION_FAILED"),
    MANAGEMENT_ACCESS_DENIED("MON.API.MANAGEMENT_ACCESS_DENIED"),
    MANAGEMENT_NOT_FOUND("MON.API.MANAGEMENT_NOT_FOUND"),
    MANAGEMENT_CONFLICT("MON.API.MANAGEMENT_CONFLICT"),
    MONITORING_SYSTEM_UNAVAILABLE("MON.API.MONITORING_SYSTEM_UNAVAILABLE"),
    ALERT_NOT_FOUND("MON.API.ALERT_NOT_FOUND"),
    INVALID_ALERT_TRANSITION("MON.API.INVALID_ALERT_TRANSITION"),
    ENFORCEMENT_HANDLER_REQUIRED("MON.API.ENFORCEMENT_HANDLER_REQUIRED"),
    ACTION_BLOCKED("MON.API.ACTION_BLOCKED"),
    PERSISTENCE_OPERATION_FAILED("MON.API.PERSISTENCE_OPERATION_FAILED");

    private final String code;

    MonitoringErrorCode(String code) {
        this.code = code;
    }

    /** Returns the stable external code. */
    public String getCode() {
        return code;
    }

    @Override
    public CodeFamily getFamily() {
        return CodeFamily.API_ERROR;
    }
}
